-- ddl-auto: update が ALTER をサボる既存DB向けの保険。
-- IF NOT EXISTS にしているので、新規DB（Hibernate がテーブル生成）でも害は無い。
ALTER TABLE IF EXISTS shift_requests ADD COLUMN IF NOT EXISTS status VARCHAR(24);

-- らくしふ風モーダル: 勤務メモ・タスク・休憩時間
ALTER TABLE IF EXISTS shift_assignments ADD COLUMN IF NOT EXISTS work_memo VARCHAR(500);
ALTER TABLE IF EXISTS shift_assignments ADD COLUMN IF NOT EXISTS tasks VARCHAR(500);
CREATE TABLE IF NOT EXISTS shift_assignment_breaks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL,
    start_time VARCHAR(5) NOT NULL,
    end_time VARCHAR(5) NOT NULL,
    sort_order INT,
    CONSTRAINT fk_break_assignment FOREIGN KEY (assignment_id) REFERENCES shift_assignments(id) ON DELETE CASCADE
);
